function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMATRIX1, X2, YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 15-Jan-2019 15:50:42

% Create figure
figure1 = figure('PaperSize',[20.99999864 29.69999902]);

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','YScale','log',...
    'XMinorTick','on',...
    'XScale','log',...
    'XTick',[10 100 1000 10000 100000 1000000],...
    'FontSize',20);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[10 1000000]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1(1:2,:),'LineWidth',2);
set(loglog1(1),'DisplayName','MH-logRW','Marker','o','Color',[0 0 1]);
set(loglog1(2),'DisplayName','MH-logTRW','Marker','^','Color',[1 0 0]);

% Create multiple lines using matrix input to loglog
loglog2 = loglog(X2,YMatrix2,'LineWidth',2,'LineStyle','--');
set(loglog2(1),'DisplayName','PAIS-logRW','Marker','o',...
    'Color',[0 0.749019622802734 0.749019622802734]);
set(loglog2(2),'DisplayName','PAIS-logTRW','Marker','^',...
    'Color',[0.87058824300766 0.490196079015732 0]);



loglog3 = loglog(X1,YMatrix1(3,:),'LineWidth',2);
set(loglog3,'DisplayName','$\mathcal{O}(1/\sqrt{N})$','LineStyle','--',...
    'Color',[0 0 0]);

% Create xlabel
xlabel('Number of samples','Margin',2,'FontSize',20,'Interpreter','latex');

% Create ylabel
ylabel('relative error','Margin',2,'FontSize',20,'Interpreter','latex');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southwest','Interpreter','latex','FontSize',20,...
    'EdgeColor',[0 0 0]);

